from pathlib import Path

sys.path.extend(["./workflow/scripts/python"])
from common.config import FCSConfig, FlowRepoSrc

config = FCSConfig.parse_obj(config)

tools_dir = Path("resources/tools")
aspera_base_dir = tools_dir / "immport-data-download-tool"


rule download_aspera:
    output:
        aspera_base_dir / "aspera" / "cli" / "etc" / "aspera-license",
    params:
        url="https://downloads.immport.org/data/download/tool/immport-data-download-tool.zip",
        dst=f"{aspera_base_dir}.zip",
    shell:
        """
        curl -SsqLf -o {params.dst} {params.url} && \
        unzip -q -o {params.dst} -d $(dirname {aspera_base_dir}) && \
        rm -f {params.dst}
        """


rule download_immport:
    input:
        aspera=rules.download_aspera.output[0],
    output:
        "resources/immport/downloaded.txt",
    log:
        "results/log/immport",
    script:
        "scripts/python/immport/download_immport.py"


rule download_misc_repos:
    output:
        "resources/misc_repo/{id}/.downloaded.txt",
    script:
        "scripts/python/fcsio/download_archive.py"


# these can't be downloaded automatically, so the user will need to extract them
# into the paths listed here manually
rule list_flow_repo_files:
    output:
        "resources/flow_repository/downloaded.txt",
    params:
        targets=lambda wildcards, output: [
            str(Path(output[0]).parent / f.src.fr_id / n)
            for f in config.test_files
            if isinstance(f.src, FlowRepoSrc)
            for n in f.src.file_names
        ],
    run:
        from pathlib import Path

        with open(output[0], "w") as f:
            for t in params.targets:
                f.write(t + "\n")


rule list_all_fcs_files:
    input:
        misc=expand(rules.download_misc_repos.output, id=config.get_misc_dataset_ids()),
        immport=rules.download_immport.output,
        fr=rules.list_flow_repo_files.output,
    output:
        "resources/all_fcs_files.txt",
    shell:
        """
        cat {input.misc} \
            {input.immport} \
            {input.fr} \
        > {output}
        """


read_test_out = Path("results/test_read")
read_test_diag = Path("results") / "diagnostics"


rule test_read:
    input:
        rules.list_all_fcs_files.output,
    output:
        fcs=read_test_out / "fcs" / "tested.txt",
        # diagnostic dump
        offsets=read_test_diag / "offsets.tsv",
        overflow=read_test_diag / "overflow.tsv",
        overlap=read_test_diag / "overlap.tsv",
        key_val_pairs=read_test_diag / "key_val_pairs.tsv",
        tokens=read_test_diag / "tokens.tsv",
        fixed_scales=read_test_diag / "fixed_scales.tsv",
        original_names=read_test_diag / "original_names.tsv",
        overrange=read_test_diag / "overrange.tsv",
        version_scores=read_test_diag / "version_scores.tsv",
        padding=read_test_diag / "padding.tsv",
        dark_bytes=read_test_diag / "dark_bytes.tsv",
        misc=read_test_diag / "misc.tsv",
    log:
        "results/log/test_read.log",
    threads: 20
    script:
        "scripts/python/fcsio/test_read.py"


rule test_double_parse:
    input:
        original=rules.list_all_fcs_files.output[0],
        std=rules.test_read.output.fcs,
    output:
        "results/double_parse/pass.txt",
    log:
        "results/log/double_parse.log",
    threads: 20
    script:
        "scripts/python/fcsio/test_double_parse.py"


# read all important metadata from TEXT; this is done separately from reading
# the datasets initially since just reading TEXT (no DATA) is cheap and allows
# us to tweak this rule without forcing all the FCS to be reread
rule compile_metadata:
    input:
        rules.list_all_fcs_files.output[0],
    output:
        file_paths="results/reports/files_paths.tsv",
        machine_table="results/reports/machines.tsv",
        time_keywords="results/reports/time_keywords.tsv",
        other_root_keywords="results/reports/other_root_keywords.tsv",
        unstained_centers="results/reports/unstained_centers.tsv",
        gated_meas="results/reports/gated_meas.tsv",
        nonstd="results/reports/nonstd.tsv",
        mixed_schema="results/reports/mixed_schema.tsv",
        var_uint_schema="results/reports/var_uint_schema.tsv",
        ascii_schema="results/reports/ascii_schema.tsv",
        matrix_schema="results/reports/matrix_schema.tsv",
        ranges="results/reports/ranges.tsv",
        byteord="results/reports/byteord.tsv",
        meas_keywords="results/reports/meas_keywords.tsv",
    threads: 20
    script:
        "scripts/python/fcsio/compile_metadata.py"


rule compile_errors:
    input:
        **rules.test_read.output,
        machines=rules.compile_metadata.output.machine_table,
    output:
        table="results/reports/errors.tsv",
        plot="results/reports/errors.pdf",
    conda:
        "envs/tidyverse.yml"
    script:
        "scripts/R/compile_errors.R"


rule compile_features:
    input:
        **rules.compile_metadata.output,
        **rules.test_read.output,
    output:
        # tables
        kw_usage="results/features/kw_usage.tsv",
        schema="results/features/schema.tsv",
        # plots
        plot_datasets="results/features/datasets.pdf",
        plot_supp_text="results/features/supp_text.pdf",
        plot_analysis="results/features/analysis.pdf",
        plot_other_seg="results/features/other_seg.pdf",
        plot_crc="results/features/crc.pdf",
        plot_dark="results/features/dark.pdf",
        plot_scaling="results/features/scaling.pdf",
        plot_byteord="results/features/byteord.pdf",
        plot_schema="results/features/schema.pdf",
        plot_kw_usage="results/features/kw_usage.pdf",
    conda:
        "envs/tidyverse.yml"
    script:
        "scripts/R/compile_features.R"


rule all:
    input:
        rules.test_read.output,
        rules.test_double_parse.output,
        rules.compile_metadata.output,
        rules.compile_errors.output,
        rules.compile_features.output,
